### PR TITLE
Replace Triangle with delaunator-cpp

### LINKED ISSUE #4: Figure out why triangle fails when triangulating very large pointclouds (> 45M)
`dem_gen.py` fails when trying to triangulate very large pointclouds (> 45 million points). This is temporarily fixed by thinning the point cloud if it is too big: https://github.com/Kortforsyningen/DHMQC/blob/master/qc/dem_gen.py#L572-L578 . If it turns out that triangle can't be fixed, a better way of downsampling the pointcloud is needed.

### LINKED ISSUE #8: Find a suitable replacement for Triangle
Triangle is a very nice library but it in terms of licensing it is horrible. A new gridding library would allow us to simplify the install-script and let us distribute a pre-build package.

Alternatives to Triangle includes:

* [Qhull](http://qhull.org/), [python bindings](https://github.com/materialsvirtuallab/pyhull)
* [MeshPy](https://documen.tician.de/meshpy/)
* [FLANN](https://github.com/mariusmuja/flann) (we would have to change gridding strategy completely, since it is inverse distance weighted interpolation)

We need to figure out if any of the alternatives are usable. Are they fast enough? Producing the desired results? How big a change to the existing code-base is needed? Any license issues?

### PR DESCRIPTION
**Pull request by plimkilde**
Closes #8 

This PR gets rid of all references to the Triangle library. This way, DHMQC will have no nonfree dependencies.

Triangle is replaced by [delaunator-cpp](https://github.com/delfrrr/delaunator-cpp). This is an easy-to-compile and reasonably fast C++ library, though it apparently does not use exact geometric predicates like Triangle. ([Geogram](http://alice.loria.fr/software/geogram/doc/html/index.html) should be easy to substitute for delaunator-cpp, but has more complicated build requirements.)

All tests are passing, and `dem_gen` appears to be functionally identical to the Triangle-based version. The code base has been manually reviewed to check for further calls to now-removed functions.

This PR introduces the requirement of a C++ compiler (`g++` only for the moment). The build script has been adapted to this with a slightly dirty hack since it does not fit too well within DHMQC's existing assumptions,

In theory this PR should also close #4, but there are still some issues with very large point clouds. This might be due to the use of C `int`s as used for Triangle's indexing, which possibly overflow in intermediate results. This PR is intended in scope to provide a drop-in replacement for Triangle, and hence does not address the data type used for indexing.

### CODE REVIEW

**Comment by plimkilde** [comment]
Finally got it all working. It seems `wget` got caught up in some garbled redirect URLs.

**Comment by kbevers** [comment]
Good effort! I suggest you squash the (many) commits into two: One for the actual changes and one that deals with CI settings not related to the Triangle replacement (wget etc).

**Comment by plimkilde** [comment]
Agreed, the CI adjustments got a bit out of hand for this one. I'll have a look at it.

**Comment by plimkilde** [comment]
In practice, I found it difficult to cleanly rebase the "CI" commits in this case, and I've therefore duplicated those changes into #24 and #23, then merged from master into this branch.

**Pull request merged**
